/*
 *
 * UserProfilePage constants
 *
 */

export const DESTROY_USER_PROFILE_ACTION = 'app/UserProfilePage/DESTROY_USER_PROFILE';

export const LOAD_USER_PROFILE_ACTION = 'app/UserProfilePage/LOAD_USER_PROFILE';
export const LOAD_USER_PROFILE_SUCCESS_ACTION = 'app/UserProfilePage/LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAILED_ACTION = 'app/UserProfilePage/LOAD_USER_PROFILE_FAILED';

export const SUBMIT_USER_PROFILE_ACTION = 'app/UserProfilePage/SUBMIT_USER_PROFILE';
export const SUBMIT_USER_PROFILE_SUCCESS_ACTION = 'app/UserProfilePage/SUBMIT_USER_PROFILE_SUCCESS';
export const SUBMIT_USER_PROFILE_FAILED_ACTION = 'app/UserProfilePage/SUBMIT_USER_PROFILE_FAILED';

export const UPDATE_AVATAR_ACTION = 'app/UserProfilePage/UPDATE_AVATAR';
export const UPDATE_AVATAR_SUCCESS_ACTION = 'app/UserProfilePage/UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILED_ACTION = 'app/UserProfilePage/UPDATE_AVATAR_FAILED';
