// flow-typed signature: 30fa5f761a9d83e82f2238c4b20b5a74
// flow-typed version: <<STUB>>/eases_v^1.0.8/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eases'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eases' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eases/back-in-out' {
  declare module.exports: any;
}

declare module 'eases/back-in' {
  declare module.exports: any;
}

declare module 'eases/back-out' {
  declare module.exports: any;
}

declare module 'eases/bounce-in-out' {
  declare module.exports: any;
}

declare module 'eases/bounce-in' {
  declare module.exports: any;
}

declare module 'eases/bounce-out' {
  declare module.exports: any;
}

declare module 'eases/circ-in-out' {
  declare module.exports: any;
}

declare module 'eases/circ-in' {
  declare module.exports: any;
}

declare module 'eases/circ-out' {
  declare module.exports: any;
}

declare module 'eases/cubic-in-out' {
  declare module.exports: any;
}

declare module 'eases/cubic-in' {
  declare module.exports: any;
}

declare module 'eases/cubic-out' {
  declare module.exports: any;
}

declare module 'eases/elastic-in-out' {
  declare module.exports: any;
}

declare module 'eases/elastic-in' {
  declare module.exports: any;
}

declare module 'eases/elastic-out' {
  declare module.exports: any;
}

declare module 'eases/expo-in-out' {
  declare module.exports: any;
}

declare module 'eases/expo-in' {
  declare module.exports: any;
}

declare module 'eases/expo-out' {
  declare module.exports: any;
}

declare module 'eases/linear' {
  declare module.exports: any;
}

declare module 'eases/quad-in-out' {
  declare module.exports: any;
}

declare module 'eases/quad-in' {
  declare module.exports: any;
}

declare module 'eases/quad-out' {
  declare module.exports: any;
}

declare module 'eases/quart-in-out' {
  declare module.exports: any;
}

declare module 'eases/quart-in' {
  declare module.exports: any;
}

declare module 'eases/quart-out' {
  declare module.exports: any;
}

declare module 'eases/quint-in-out' {
  declare module.exports: any;
}

declare module 'eases/quint-in' {
  declare module.exports: any;
}

declare module 'eases/quint-out' {
  declare module.exports: any;
}

declare module 'eases/sine-in-out' {
  declare module.exports: any;
}

declare module 'eases/sine-in' {
  declare module.exports: any;
}

declare module 'eases/sine-out' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eases/back-in-out.js' {
  declare module.exports: $Exports<'eases/back-in-out'>;
}
declare module 'eases/back-in.js' {
  declare module.exports: $Exports<'eases/back-in'>;
}
declare module 'eases/back-out.js' {
  declare module.exports: $Exports<'eases/back-out'>;
}
declare module 'eases/bounce-in-out.js' {
  declare module.exports: $Exports<'eases/bounce-in-out'>;
}
declare module 'eases/bounce-in.js' {
  declare module.exports: $Exports<'eases/bounce-in'>;
}
declare module 'eases/bounce-out.js' {
  declare module.exports: $Exports<'eases/bounce-out'>;
}
declare module 'eases/circ-in-out.js' {
  declare module.exports: $Exports<'eases/circ-in-out'>;
}
declare module 'eases/circ-in.js' {
  declare module.exports: $Exports<'eases/circ-in'>;
}
declare module 'eases/circ-out.js' {
  declare module.exports: $Exports<'eases/circ-out'>;
}
declare module 'eases/cubic-in-out.js' {
  declare module.exports: $Exports<'eases/cubic-in-out'>;
}
declare module 'eases/cubic-in.js' {
  declare module.exports: $Exports<'eases/cubic-in'>;
}
declare module 'eases/cubic-out.js' {
  declare module.exports: $Exports<'eases/cubic-out'>;
}
declare module 'eases/elastic-in-out.js' {
  declare module.exports: $Exports<'eases/elastic-in-out'>;
}
declare module 'eases/elastic-in.js' {
  declare module.exports: $Exports<'eases/elastic-in'>;
}
declare module 'eases/elastic-out.js' {
  declare module.exports: $Exports<'eases/elastic-out'>;
}
declare module 'eases/expo-in-out.js' {
  declare module.exports: $Exports<'eases/expo-in-out'>;
}
declare module 'eases/expo-in.js' {
  declare module.exports: $Exports<'eases/expo-in'>;
}
declare module 'eases/expo-out.js' {
  declare module.exports: $Exports<'eases/expo-out'>;
}
declare module 'eases/index' {
  declare module.exports: $Exports<'eases'>;
}
declare module 'eases/index.js' {
  declare module.exports: $Exports<'eases'>;
}
declare module 'eases/linear.js' {
  declare module.exports: $Exports<'eases/linear'>;
}
declare module 'eases/quad-in-out.js' {
  declare module.exports: $Exports<'eases/quad-in-out'>;
}
declare module 'eases/quad-in.js' {
  declare module.exports: $Exports<'eases/quad-in'>;
}
declare module 'eases/quad-out.js' {
  declare module.exports: $Exports<'eases/quad-out'>;
}
declare module 'eases/quart-in-out.js' {
  declare module.exports: $Exports<'eases/quart-in-out'>;
}
declare module 'eases/quart-in.js' {
  declare module.exports: $Exports<'eases/quart-in'>;
}
declare module 'eases/quart-out.js' {
  declare module.exports: $Exports<'eases/quart-out'>;
}
declare module 'eases/quint-in-out.js' {
  declare module.exports: $Exports<'eases/quint-in-out'>;
}
declare module 'eases/quint-in.js' {
  declare module.exports: $Exports<'eases/quint-in'>;
}
declare module 'eases/quint-out.js' {
  declare module.exports: $Exports<'eases/quint-out'>;
}
declare module 'eases/sine-in-out.js' {
  declare module.exports: $Exports<'eases/sine-in-out'>;
}
declare module 'eases/sine-in.js' {
  declare module.exports: $Exports<'eases/sine-in'>;
}
declare module 'eases/sine-out.js' {
  declare module.exports: $Exports<'eases/sine-out'>;
}
