// flow-typed signature: 93f571c80b8a08fef178d398e436a3b7
// flow-typed version: <<STUB>>/eventsource-polyfill_v0.9.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eventsource-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eventsource-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eventsource-polyfill/dist/browserify-eventsource' {
  declare module.exports: any;
}

declare module 'eventsource-polyfill/dist/eventsource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eventsource-polyfill/dist/browserify-eventsource.js' {
  declare module.exports: $Exports<'eventsource-polyfill/dist/browserify-eventsource'>;
}
declare module 'eventsource-polyfill/dist/eventsource.js' {
  declare module.exports: $Exports<'eventsource-polyfill/dist/eventsource'>;
}
