// flow-typed signature: 60542f7ecdf8445a8d57884cbeefd011
// flow-typed version: <<STUB>>/redux-auth_vhttps://bitbucket.org/arabellatech/redux-auth.git/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-auth/flow-typed/npm/@kadira/storybook_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint-config-airbnb-base_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-auth/internals/testing/test-bundler' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/api/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/FormError/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/RequestPasswordResetForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/RequestPasswordResetForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/ResetPasswordForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/ResetPasswordForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/SignInForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/SignInForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/SignUpForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/SignUpForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/WrappedInput/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/components/WrappedInput/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/hocs' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/AuthenticationProvider/utils' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/RequestPasswordResetPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/ResetPasswordPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignInPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignOutPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignOutPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignOutPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignOutPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/containers/SignUpPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/hocs/AuthWrappers/UserHasRole' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsAdmin' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsAuthenticated' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsNotAuthenticated' {
  declare module.exports: any;
}

declare module 'redux-auth/lib/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/api/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/api/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/FormError/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/FormError/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/RequestPasswordResetForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/RequestPasswordResetForm/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/RequestPasswordResetForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/ResetPasswordForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/ResetPasswordForm/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/ResetPasswordForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignInForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignInForm/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignInForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignUpForm/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignUpForm/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/SignUpForm/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/WrappedInput/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/WrappedInput/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/components/WrappedInput/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/hocs' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/hocs.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/reducer.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/selectors.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/utils' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/AuthenticationProvider/utils.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/reducer.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/RequestPasswordResetPage/selectors.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/reducer.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/ResetPasswordPage/selectors.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/reducer.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignInPage/selectors.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignOutPage/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/actions' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/actions.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/index.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/messages' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/reducer' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/reducer.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/sagas' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/sagas.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/selectors' {
  declare module.exports: any;
}

declare module 'redux-auth/src/containers/SignUpPage/selectors.test' {
  declare module.exports: any;
}

declare module 'redux-auth/src/hocs/AuthWrappers/UserHasRole' {
  declare module.exports: any;
}

declare module 'redux-auth/src/hocs/AuthWrappers/UserIsAdmin' {
  declare module.exports: any;
}

declare module 'redux-auth/src/hocs/AuthWrappers/UserIsAuthenticated' {
  declare module.exports: any;
}

declare module 'redux-auth/src/hocs/AuthWrappers/UserIsNotAuthenticated' {
  declare module.exports: any;
}

declare module 'redux-auth/src/index' {
  declare module.exports: any;
}

declare module 'redux-auth/stories/MyComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-auth/flow-typed/npm/@kadira/storybook_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/@kadira/storybook_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint-config-airbnb-base_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint-config-airbnb-base_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'redux-auth/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'redux-auth/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'redux-auth/index' {
  declare module.exports: $Exports<'redux-auth'>;
}
declare module 'redux-auth/index.js' {
  declare module.exports: $Exports<'redux-auth'>;
}
declare module 'redux-auth/internals/testing/test-bundler.js' {
  declare module.exports: $Exports<'redux-auth/internals/testing/test-bundler'>;
}
declare module 'redux-auth/lib/api/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/api/index'>;
}
declare module 'redux-auth/lib/components/FormError/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/FormError/index'>;
}
declare module 'redux-auth/lib/components/RequestPasswordResetForm/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/RequestPasswordResetForm/index'>;
}
declare module 'redux-auth/lib/components/RequestPasswordResetForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/RequestPasswordResetForm/messages'>;
}
declare module 'redux-auth/lib/components/ResetPasswordForm/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/ResetPasswordForm/index'>;
}
declare module 'redux-auth/lib/components/ResetPasswordForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/ResetPasswordForm/messages'>;
}
declare module 'redux-auth/lib/components/SignInForm/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/SignInForm/index'>;
}
declare module 'redux-auth/lib/components/SignInForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/SignInForm/messages'>;
}
declare module 'redux-auth/lib/components/SignUpForm/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/SignUpForm/index'>;
}
declare module 'redux-auth/lib/components/SignUpForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/SignUpForm/messages'>;
}
declare module 'redux-auth/lib/components/WrappedInput/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/WrappedInput/index'>;
}
declare module 'redux-auth/lib/components/WrappedInput/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/components/WrappedInput/messages'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/actions'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/constants'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/hocs.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/hocs'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/index'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/reducer.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/reducer'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/sagas'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/selectors.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/selectors'>;
}
declare module 'redux-auth/lib/containers/AuthenticationProvider/utils.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/AuthenticationProvider/utils'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/actions'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/constants'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/index'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/messages'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/reducer'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/sagas'>;
}
declare module 'redux-auth/lib/containers/RequestPasswordResetPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/RequestPasswordResetPage/selectors'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/actions'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/constants'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/index'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/messages'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/reducer'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/sagas'>;
}
declare module 'redux-auth/lib/containers/ResetPasswordPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/ResetPasswordPage/selectors'>;
}
declare module 'redux-auth/lib/containers/SignInPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/actions'>;
}
declare module 'redux-auth/lib/containers/SignInPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/constants'>;
}
declare module 'redux-auth/lib/containers/SignInPage/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/index'>;
}
declare module 'redux-auth/lib/containers/SignInPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/messages'>;
}
declare module 'redux-auth/lib/containers/SignInPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/reducer'>;
}
declare module 'redux-auth/lib/containers/SignInPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/sagas'>;
}
declare module 'redux-auth/lib/containers/SignInPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignInPage/selectors'>;
}
declare module 'redux-auth/lib/containers/SignOutPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignOutPage/actions'>;
}
declare module 'redux-auth/lib/containers/SignOutPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignOutPage/constants'>;
}
declare module 'redux-auth/lib/containers/SignOutPage/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignOutPage/index'>;
}
declare module 'redux-auth/lib/containers/SignOutPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignOutPage/sagas'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/actions'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/constants'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/index'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/messages'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/reducer'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/sagas'>;
}
declare module 'redux-auth/lib/containers/SignUpPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/lib/containers/SignUpPage/selectors'>;
}
declare module 'redux-auth/lib/hocs/AuthWrappers/UserHasRole.js' {
  declare module.exports: $Exports<'redux-auth/lib/hocs/AuthWrappers/UserHasRole'>;
}
declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsAdmin.js' {
  declare module.exports: $Exports<'redux-auth/lib/hocs/AuthWrappers/UserIsAdmin'>;
}
declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsAuthenticated.js' {
  declare module.exports: $Exports<'redux-auth/lib/hocs/AuthWrappers/UserIsAuthenticated'>;
}
declare module 'redux-auth/lib/hocs/AuthWrappers/UserIsNotAuthenticated.js' {
  declare module.exports: $Exports<'redux-auth/lib/hocs/AuthWrappers/UserIsNotAuthenticated'>;
}
declare module 'redux-auth/lib/index.js' {
  declare module.exports: $Exports<'redux-auth/lib/index'>;
}
declare module 'redux-auth/src/api/index.js' {
  declare module.exports: $Exports<'redux-auth/src/api/index'>;
}
declare module 'redux-auth/src/api/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/api/index.test'>;
}
declare module 'redux-auth/src/components/FormError/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/FormError/index'>;
}
declare module 'redux-auth/src/components/FormError/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/FormError/index.test'>;
}
declare module 'redux-auth/src/components/RequestPasswordResetForm/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/RequestPasswordResetForm/index'>;
}
declare module 'redux-auth/src/components/RequestPasswordResetForm/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/RequestPasswordResetForm/index.test'>;
}
declare module 'redux-auth/src/components/RequestPasswordResetForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/components/RequestPasswordResetForm/messages'>;
}
declare module 'redux-auth/src/components/ResetPasswordForm/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/ResetPasswordForm/index'>;
}
declare module 'redux-auth/src/components/ResetPasswordForm/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/ResetPasswordForm/index.test'>;
}
declare module 'redux-auth/src/components/ResetPasswordForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/components/ResetPasswordForm/messages'>;
}
declare module 'redux-auth/src/components/SignInForm/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignInForm/index'>;
}
declare module 'redux-auth/src/components/SignInForm/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignInForm/index.test'>;
}
declare module 'redux-auth/src/components/SignInForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignInForm/messages'>;
}
declare module 'redux-auth/src/components/SignUpForm/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignUpForm/index'>;
}
declare module 'redux-auth/src/components/SignUpForm/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignUpForm/index.test'>;
}
declare module 'redux-auth/src/components/SignUpForm/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/components/SignUpForm/messages'>;
}
declare module 'redux-auth/src/components/WrappedInput/index.js' {
  declare module.exports: $Exports<'redux-auth/src/components/WrappedInput/index'>;
}
declare module 'redux-auth/src/components/WrappedInput/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/components/WrappedInput/index.test'>;
}
declare module 'redux-auth/src/components/WrappedInput/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/components/WrappedInput/messages'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/actions'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/actions.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/constants'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/hocs.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/hocs'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/hocs.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/hocs.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/index'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/index.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/reducer.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/reducer'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/reducer.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/reducer.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/sagas'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/sagas.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/selectors.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/selectors'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/selectors.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/selectors.test'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/utils.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/utils'>;
}
declare module 'redux-auth/src/containers/AuthenticationProvider/utils.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/AuthenticationProvider/utils.test'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/actions'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/actions.test'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/constants'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/index'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/index.test'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/messages'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/reducer'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/reducer.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/reducer.test'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/sagas'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/sagas.test'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/selectors'>;
}
declare module 'redux-auth/src/containers/RequestPasswordResetPage/selectors.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/RequestPasswordResetPage/selectors.test'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/actions'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/actions.test'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/constants'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/index'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/index.test'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/messages'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/reducer'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/reducer.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/reducer.test'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/sagas'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/sagas.test'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/selectors'>;
}
declare module 'redux-auth/src/containers/ResetPasswordPage/selectors.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/ResetPasswordPage/selectors.test'>;
}
declare module 'redux-auth/src/containers/SignInPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/actions'>;
}
declare module 'redux-auth/src/containers/SignInPage/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/actions.test'>;
}
declare module 'redux-auth/src/containers/SignInPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/constants'>;
}
declare module 'redux-auth/src/containers/SignInPage/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/index'>;
}
declare module 'redux-auth/src/containers/SignInPage/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/index.test'>;
}
declare module 'redux-auth/src/containers/SignInPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/messages'>;
}
declare module 'redux-auth/src/containers/SignInPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/reducer'>;
}
declare module 'redux-auth/src/containers/SignInPage/reducer.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/reducer.test'>;
}
declare module 'redux-auth/src/containers/SignInPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/sagas'>;
}
declare module 'redux-auth/src/containers/SignInPage/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/sagas.test'>;
}
declare module 'redux-auth/src/containers/SignInPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/selectors'>;
}
declare module 'redux-auth/src/containers/SignInPage/selectors.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignInPage/selectors.test'>;
}
declare module 'redux-auth/src/containers/SignOutPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/actions'>;
}
declare module 'redux-auth/src/containers/SignOutPage/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/actions.test'>;
}
declare module 'redux-auth/src/containers/SignOutPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/constants'>;
}
declare module 'redux-auth/src/containers/SignOutPage/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/index'>;
}
declare module 'redux-auth/src/containers/SignOutPage/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/index.test'>;
}
declare module 'redux-auth/src/containers/SignOutPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/sagas'>;
}
declare module 'redux-auth/src/containers/SignOutPage/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignOutPage/sagas.test'>;
}
declare module 'redux-auth/src/containers/SignUpPage/actions.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/actions'>;
}
declare module 'redux-auth/src/containers/SignUpPage/actions.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/actions.test'>;
}
declare module 'redux-auth/src/containers/SignUpPage/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/constants'>;
}
declare module 'redux-auth/src/containers/SignUpPage/index.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/index'>;
}
declare module 'redux-auth/src/containers/SignUpPage/index.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/index.test'>;
}
declare module 'redux-auth/src/containers/SignUpPage/messages.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/messages'>;
}
declare module 'redux-auth/src/containers/SignUpPage/reducer.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/reducer'>;
}
declare module 'redux-auth/src/containers/SignUpPage/reducer.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/reducer.test'>;
}
declare module 'redux-auth/src/containers/SignUpPage/sagas.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/sagas'>;
}
declare module 'redux-auth/src/containers/SignUpPage/sagas.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/sagas.test'>;
}
declare module 'redux-auth/src/containers/SignUpPage/selectors.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/selectors'>;
}
declare module 'redux-auth/src/containers/SignUpPage/selectors.test.js' {
  declare module.exports: $Exports<'redux-auth/src/containers/SignUpPage/selectors.test'>;
}
declare module 'redux-auth/src/hocs/AuthWrappers/UserHasRole.js' {
  declare module.exports: $Exports<'redux-auth/src/hocs/AuthWrappers/UserHasRole'>;
}
declare module 'redux-auth/src/hocs/AuthWrappers/UserIsAdmin.js' {
  declare module.exports: $Exports<'redux-auth/src/hocs/AuthWrappers/UserIsAdmin'>;
}
declare module 'redux-auth/src/hocs/AuthWrappers/UserIsAuthenticated.js' {
  declare module.exports: $Exports<'redux-auth/src/hocs/AuthWrappers/UserIsAuthenticated'>;
}
declare module 'redux-auth/src/hocs/AuthWrappers/UserIsNotAuthenticated.js' {
  declare module.exports: $Exports<'redux-auth/src/hocs/AuthWrappers/UserIsNotAuthenticated'>;
}
declare module 'redux-auth/src/index.js' {
  declare module.exports: $Exports<'redux-auth/src/index'>;
}
declare module 'redux-auth/stories/MyComponent.js' {
  declare module.exports: $Exports<'redux-auth/stories/MyComponent'>;
}
